import json
import time
from pathlib import Path
from typing import Dict, Any

from loguru import logger
from pipecat.observers.base_observer import BaseObserver, FramePushed
from pipecat.frames.frames import (
    VADUserStoppedSpeakingFrame,
    UserStoppedSpeakingFrame,
    TranscriptionFrame,
    LLMRunFrame,
    LLMFullResponseStartFrame,
    LLMFullResponseEndFrame,
    TextFrame,
    TTSAudioRawFrame,
    BotStartedSpeakingFrame,
    LLMContextFrame,
    MetricsFrame
)

LOGS_DIR = Path(__file__).parent / "logs"

class LatencyBreakdownObserver(BaseObserver):
    """
    Observes Pipecat frames and records high-precision timestamps 
    for every major stage in a conversational turn.
    """
    def __init__(self, call_id: str):
        super().__init__()
        self.call_id = call_id
        self.turn_records = []
        self._turn_index = 0
        self._current_turn: Dict[str, Any] = self._new_turn()
        LOGS_DIR.mkdir(exist_ok=True)
        
    def _new_turn(self) -> Dict[str, Any]:
        return {
            "turn_index": self._turn_index + 1,
            "transcript": "",
            "deterministic_path": False,
            "tool_calls": 0,
            "prompt_tokens": 0,
            "completion_tokens": 0,
            "timestamps": {}
        }
        
    def _flush_turn(self):
        if not self._current_turn["timestamps"]:
            return
            
        # Only save if we actually got to the end of the turn (bot started speaking)
        # or if it was a valid turn that got cancelled.
        if "bot_started" in self._current_turn["timestamps"]:
            self.turn_records.append(self._current_turn)
            self._save_to_disk()
            
        self._turn_index += 1
        self._current_turn = self._new_turn()

    def _save_to_disk(self):
        filepath = LOGS_DIR / f"latency_{self.call_id}.json"
        filepath.write_text(json.dumps(self.turn_records, indent=2, default=str))

    async def on_push_frame(self, data: FramePushed):
        frame = data.frame
        ts = time.time()
        
        # 1. VAD stops
        if isinstance(frame, VADUserStoppedSpeakingFrame):
            # Only record if we haven't already for this turn
            if "vad_stop" not in self._current_turn["timestamps"]:
                self._current_turn["timestamps"]["vad_stop"] = ts
                
        # 2. End-of-turn detector stops the turn
        elif isinstance(frame, UserStoppedSpeakingFrame):
            self._current_turn["timestamps"]["turn_stop"] = ts
            
        # 3. Final STT transcript
        elif isinstance(frame, TranscriptionFrame) and frame.text.strip():
            self._current_turn["timestamps"]["stt_final"] = ts
            self._current_turn["transcript"] = frame.text
            
        # Intercept LLMContextFrame to determine if deterministic extraction worked
        elif isinstance(frame, LLMContextFrame):
            # If tools are empty, deterministic path succeeded
            if frame.context and not frame.context.tools:
                self._current_turn["deterministic_path"] = True
            else:
                self._current_turn["deterministic_path"] = False
                
        # 4. LLM request starts
        elif isinstance(frame, LLMRunFrame):
            if "llm_run" not in self._current_turn["timestamps"]:
                self._current_turn["timestamps"]["llm_run"] = ts
                
        # 5. LLM first token received
        elif isinstance(frame, LLMFullResponseStartFrame):
            if "llm_first_token" not in self._current_turn["timestamps"]:
                self._current_turn["timestamps"]["llm_first_token"] = ts
                
        # 6. First text chunk sent to TTS (from LLM)
        elif isinstance(frame, TextFrame):
            # The LLM outputs TextFrames. We only care about the first one.
            if "first_text_to_tts" not in self._current_turn["timestamps"]:
                # Ensure it's coming from an LLM service (or going to TTS)
                producer_name = data.source.__class__.__name__
                if "LLM" in producer_name or "LLMAssistantContextAggregator" in producer_name:
                    self._current_turn["timestamps"]["first_text_to_tts"] = ts
                    
        # 7. First audio chunk generated by TTS
        elif isinstance(frame, TTSAudioRawFrame):
            if "first_tts_audio" not in self._current_turn["timestamps"]:
                self._current_turn["timestamps"]["first_tts_audio"] = ts
                
        # 8. Bot starts speaking (transport playback)
        elif isinstance(frame, BotStartedSpeakingFrame):
            if "bot_started" not in self._current_turn["timestamps"]:
                self._current_turn["timestamps"]["bot_started"] = ts
                self._flush_turn() # Complete the turn record
            
        # Tokens
        elif isinstance(frame, MetricsFrame):
            for m in frame.data:
                # LLMUsageMetricsData has prompt_tokens and completion_tokens
                pt = getattr(m, "prompt_tokens", None)
                ct = getattr(m, "completion_tokens", None)
                if pt is not None:
                    self._current_turn["prompt_tokens"] += pt
                if ct is not None:
                    self._current_turn["completion_tokens"] += ct
